/**
 * Landmark research papers shown in the Research Papers section. Citation
 * counts are illustrative placeholders (the Learn surface is offline). Authors,
 * years and titles are accurate. Foundation papers carry the "Foundation" tag;
 * recent breakthroughs carry "New".
 */

import type { Paper, PaperCategoryCard } from "./types";

/** Total shown in the section header — a rounded, illustrative figure. */
export const PAPER_TOTAL = "2,456";

export const PAPERS: ReadonlyArray<Paper> = [
  {
    id: "attention",
    title: "Attention Is All You Need",
    authors: "A. Vaswani et al.",
    year: 2017,
    category: "Transformers",
    tag: "Foundation",
    summary: "Introduced the Transformer architecture, replacing RNNs for sequence modelling.",
    citations: 22357,
    readMinutes: 22,
    href: "https://arxiv.org/abs/1706.03762",
  },
  {
    id: "resnet",
    title: "Deep Residual Learning for Image Recognition",
    authors: "K. He et al.",
    year: 2015,
    category: "Computer Vision",
    tag: "Foundation",
    summary: "Introduced ResNet and residual connections, enabling very deep networks.",
    citations: 27152,
    readMinutes: 18,
    href: "https://arxiv.org/abs/1512.03385",
  },
  {
    id: "bert",
    title: "BERT: Pre-training of Deep Bidirectional Transformers",
    authors: "J. Devlin et al.",
    year: 2018,
    category: "Large Language Models",
    tag: "Foundation",
    summary: "Introduced BERT, a milestone in NLP pre-training and transfer learning.",
    citations: 31768,
    readMinutes: 18,
    href: "https://arxiv.org/abs/1810.04805",
  },
  {
    id: "gan",
    title: "Generative Adversarial Networks",
    authors: "I. Goodfellow et al.",
    year: 2014,
    category: "Optimization",
    tag: "Foundation",
    summary: "Introduced GANs, a new framework for generative modelling.",
    citations: 31766,
    readMinutes: 16,
    href: "https://arxiv.org/abs/1406.2661",
  },
  {
    id: "gpt3",
    title: "Language Models are Few-Shot Learners",
    authors: "T. Brown et al.",
    year: 2020,
    category: "Large Language Models",
    tag: "Foundation",
    summary: "The GPT-3 paper that demonstrated the power of scaling language models.",
    citations: 18999,
    readMinutes: 45,
    href: "https://arxiv.org/abs/2005.14165",
  },
  {
    id: "rope",
    title: "RoFormer: Enhanced Transformer with Rotary Position Embedding",
    authors: "J. Su et al.",
    year: 2021,
    category: "Transformers",
    tag: "Technique",
    summary: "Introduced Rotary Positional Embedding (RoPE), now standard in modern LLMs.",
    citations: 3120,
    readMinutes: 12,
    href: "https://arxiv.org/abs/2104.09864",
  },
  {
    id: "lora",
    title: "LoRA: Low-Rank Adaptation of Large Language Models",
    authors: "E. Hu et al.",
    year: 2021,
    category: "Optimization",
    tag: "Technique",
    summary: "Parameter-efficient fine-tuning by learning small low-rank weight updates.",
    citations: 6200,
    readMinutes: 14,
    href: "https://arxiv.org/abs/2106.09685",
  },
  {
    id: "gpt4",
    title: "GPT-4 Technical Report",
    authors: "OpenAI",
    year: 2023,
    category: "Multimodal",
    tag: "New",
    summary: "Describes GPT-4, a large multimodal model with advanced reasoning capabilities.",
    citations: 8808,
    readMinutes: 40,
    href: "https://arxiv.org/abs/2303.08774",
  },
  {
    id: "palm",
    title: "PaLM: Scaling Language Modeling with Pathways",
    authors: "A. Chowdhery et al.",
    year: 2022,
    category: "Large Language Models",
    tag: "New",
    summary: "Introduced PaLM, a 540B-parameter model trained with the Pathways system.",
    citations: 6312,
    readMinutes: 35,
    href: "https://arxiv.org/abs/2204.02311",
  },
  {
    id: "chinchilla",
    title: "Training Compute-Optimal Large Language Models",
    authors: "J. Hoffmann et al.",
    year: 2022,
    category: "Optimization",
    tag: "New",
    summary: "The Chinchilla paper — optimal performance balances model size and data.",
    citations: 5057,
    readMinutes: 20,
    href: "https://arxiv.org/abs/2203.15556",
  },
  {
    id: "llama2",
    title: "Llama 2: Open Foundation and Fine-Tuned Chat Models",
    authors: "Meta AI",
    year: 2023,
    category: "Large Language Models",
    tag: "New",
    summary: "Open-weight LLMs enabling broad research and commercial use.",
    citations: 6910,
    readMinutes: 30,
    href: "https://arxiv.org/abs/2307.09288",
  },
  {
    id: "deepseek-r1",
    title: "DeepSeek-R1: Incentivizing Reasoning Capability in LLMs",
    authors: "DeepSeek-AI",
    year: 2025,
    category: "Reasoning",
    tag: "New",
    summary: "Reinforcement learning framework for strong, open reasoning models.",
    citations: 4992,
    readMinutes: 28,
    href: "https://arxiv.org/abs/2501.12948",
  },
  {
    id: "ddpm",
    title: "Denoising Diffusion Probabilistic Models",
    authors: "J. Ho et al.",
    year: 2020,
    category: "Multimodal",
    tag: "Technique",
    summary: "Established diffusion models as a leading approach to image generation.",
    citations: 11400,
    readMinutes: 22,
    href: "https://arxiv.org/abs/2006.11239",
  },
  {
    id: "instructgpt",
    title: "Training Language Models to Follow Instructions (InstructGPT)",
    authors: "L. Ouyang et al.",
    year: 2022,
    category: "Reinforcement Learning",
    tag: "Technique",
    summary: "Showed RLHF makes models markedly more helpful and aligned.",
    citations: 9100,
    readMinutes: 24,
    href: "https://arxiv.org/abs/2203.02155",
  },
];

/** The "Browse by Category" cards. Counts are illustrative. */
export const PAPER_CATEGORY_CARDS: ReadonlyArray<PaperCategoryCard> = [
  { category: "Transformers", count: 412, tone: "purple" },
  { category: "Large Language Models", count: 612, tone: "green" },
  { category: "Multimodal", count: 273, tone: "yellow" },
  { category: "Reinforcement Learning", count: 288, tone: "red" },
  { category: "Optimization", count: 195, tone: "teal" },
  { category: "Reasoning", count: 132, tone: "blue" },
];

export type PaperTrendingTopic = Readonly<{ topic: string; count: number }>;

export const PAPER_TRENDING_TOPICS: ReadonlyArray<PaperTrendingTopic> = [
  { topic: "Reasoning in LLMs", count: 234 },
  { topic: "Long Context Models", count: 198 },
  { topic: "Multimodal AI", count: 312 },
  { topic: "AI Safety & Alignment", count: 165 },
  { topic: "Efficient Inference", count: 147 },
];

/** Filter chips across the top of the section. */
export const PAPER_FILTERS: ReadonlyArray<string> = [
  "All",
  "Foundations",
  "Transformers",
  "Large Language Models",
  "Multimodal",
  "Reinforcement Learning",
  "Optimization",
  "Reasoning",
];
