/**
 * The AI evolution timeline — the centerpiece of the Learn surface.
 *
 * A detailed, chronological account of how artificial intelligence developed
 * from Turing's 1950 thought experiment to today's frontier reasoning models.
 * Each milestone carries a tagline (master list / table), a longer summary, the
 * concrete ways it mattered, and related-concept tags. Curated and factual —
 * dates, people and contributions are accurate to the historical record.
 */

import type { DecadeEra, TimelineEvent } from "./types";

/** The decade rail shown along the top of the Timeline view. */
export const DECADE_ERAS: ReadonlyArray<DecadeEra> = [
  { decade: "1950s", title: "The Birth of AI", subtitle: "Foundations", tone: "blue" },
  { decade: "1960s", title: "Early AI Programs", subtitle: "& Optimism", tone: "teal" },
  { decade: "1970s", title: "AI Winter", subtitle: "Begins", tone: "green" },
  { decade: "1980s", title: "Expert Systems", subtitle: "Rise", tone: "yellow" },
  { decade: "1990s", title: "Statistical ML", subtitle: "Emerges", tone: "red" },
  { decade: "2000s", title: "Deep Learning", subtitle: "Foundations", tone: "purple" },
  { decade: "2010s", title: "Deep Learning", subtitle: "Breakthrough", tone: "blue" },
  { decade: "2020s", title: "Generative AI", subtitle: "Era", tone: "purple" },
];

export const TIMELINE_EVENTS: ReadonlyArray<TimelineEvent> = [
  {
    id: "turing-1950",
    year: "1950",
    sortYear: 1950,
    decade: "1950s",
    title: "Turing Publishes 'Computing Machinery and Intelligence'",
    tagline: "Introduced the Turing Test and the idea that machines can think.",
    category: "Foundation",
    impact: 5,
    figure: "Alan Turing",
    summary:
      "Alan Turing proposed an 'imitation game' — now the Turing Test — as an operational way to ask whether a machine can think. The paper laid the philosophical and theoretical foundation for the entire field that would be named six years later.",
    details: [
      "Reframed 'Can machines think?' into a testable behavioural question.",
      "Anticipated objections (consciousness, learning) still debated today.",
      "The Turing Test remains a cultural benchmark for machine intelligence.",
    ],
    relatedConcepts: ["Turing Test", "Machine Intelligence", "Philosophy of AI"],
    links: [{ label: "Original paper", href: "https://academic.oup.com/mind/article/LIX/236/433/986238" }],
  },
  {
    id: "dartmouth-1956",
    year: "1956",
    sortYear: 1956,
    decade: "1950s",
    title: "Dartmouth Conference",
    tagline: "The term 'Artificial Intelligence' was coined.",
    category: "Foundation",
    impact: 5,
    figure: "McCarthy, Minsky, Shannon, Rochester",
    summary:
      "The Dartmouth Summer Research Project, organised by John McCarthy, is widely regarded as the founding event of AI as a discipline. McCarthy coined the term 'artificial intelligence' in the proposal, and the workshop set the research agenda for a generation.",
    details: [
      "Coined the name of the field and gathered its founding figures.",
      "Framed learning and intelligence as problems solvable by machines.",
      "Seeded decades of optimism — and the expectations that triggered later winters.",
    ],
    relatedConcepts: ["Symbolic AI", "Search", "Reasoning"],
  },
  {
    id: "perceptron-1958",
    year: "1958",
    sortYear: 1958,
    decade: "1950s",
    title: "The Perceptron",
    tagline: "Rosenblatt builds the first trainable artificial neuron.",
    category: "Foundation",
    impact: 4,
    figure: "Frank Rosenblatt",
    summary:
      "Frank Rosenblatt's perceptron was an early neural network that could learn to classify patterns by adjusting weights — the conceptual ancestor of every modern neural net. Implemented in hardware as the Mark I Perceptron, it captured the public imagination.",
    details: [
      "First learning algorithm for an artificial neuron with adjustable weights.",
      "Demonstrated machines could improve at a task from examples.",
      "Its limits (Minsky & Papert, 1969) later cooled neural-net research for years.",
    ],
    relatedConcepts: ["Neural Networks", "Perceptron", "Supervised Learning"],
  },
  {
    id: "unimate-1961",
    year: "1961",
    sortYear: 1961,
    decade: "1960s",
    title: "First Industrial Robot – Unimate",
    tagline: "The first robot deployed on a factory line.",
    category: "Robotics",
    impact: 3,
    figure: "George Devol, Joseph Engelberger",
    summary:
      "Unimate, installed at a General Motors plant, was the first industrial robot — performing dangerous die-casting and welding tasks. It marked the start of automation and embodied AI in the physical world.",
    details: [
      "Proved programmable machines could replace humans in hazardous tasks.",
      "Launched the industrial-robotics industry.",
      "Separated 'embodied' automation from symbolic-reasoning AI research.",
    ],
    relatedConcepts: ["Robotics", "Automation", "Control"],
  },
  {
    id: "eliza-1966",
    year: "1966",
    sortYear: 1966,
    decade: "1960s",
    title: "ELIZA – First Chatbot",
    tagline: "A program that could simulate conversation.",
    category: "NLP",
    impact: 3,
    figure: "Joseph Weizenbaum",
    summary:
      "ELIZA, written at MIT, mimicked a Rogerian psychotherapist using simple pattern-matching and canned responses. Despite having no understanding, users attributed real empathy to it — the 'ELIZA effect' that still shapes how people relate to chatbots.",
    details: [
      "First widely-known conversational program.",
      "Revealed how readily humans anthropomorphise software.",
      "A direct ancestor in spirit of today's conversational assistants.",
    ],
    relatedConcepts: ["Natural Language Processing", "Pattern Matching", "Chatbots"],
  },
  {
    id: "ai-winter-1970s",
    year: "1970s",
    sortYear: 1970,
    decade: "1970s",
    title: "The First AI Winter",
    tagline: "Funding cuts and reduced interest in AI research.",
    category: "History",
    impact: 2,
    summary:
      "After a decade of grand promises, progress stalled against the hard limits of 1970s compute and the combinatorial explosion of search. The Lighthill Report (1973) in the UK and tightening US funding triggered a prolonged 'winter' of scepticism and scarce money.",
    details: [
      "Over-promising met the reality of limited hardware and brittle methods.",
      "Government funding (DARPA, UK research councils) was sharply curtailed.",
      "A recurring cautionary pattern: hype cycles followed by corrections.",
    ],
    relatedConcepts: ["Combinatorial Explosion", "Funding", "Hype Cycle"],
  },
  {
    id: "backprop-1986",
    year: "1986",
    sortYear: 1986,
    decade: "1980s",
    title: "Backpropagation Popularised",
    tagline: "Rumelhart, Hinton & Williams make deep nets trainable.",
    category: "Deep Learning",
    impact: 4,
    figure: "Rumelhart, Hinton & Williams",
    summary:
      "Their landmark paper showed how the backpropagation algorithm could efficiently train multi-layer neural networks by propagating error gradients backward through the layers — overcoming the perceptron's single-layer limits and underpinning essentially all deep learning since.",
    details: [
      "Made training of multi-layer (deep) networks practical.",
      "Provided the gradient-based learning rule used by every modern model.",
      "Set the stage for the deep-learning revival two decades later.",
    ],
    relatedConcepts: ["Backpropagation", "Gradient Descent", "Neural Networks"],
  },
  {
    id: "expert-systems-1980s",
    year: "1980s",
    sortYear: 1987,
    decade: "1980s",
    title: "Expert Systems Boom",
    tagline: "Commercial success of rule-based AI systems.",
    category: "Expert Systems",
    impact: 2,
    summary:
      "Rule-based 'expert systems' such as XCON encoded human specialist knowledge as if-then rules and found real commercial use, briefly making AI a billion-dollar industry. Their brittleness and maintenance cost led to a second AI winter by the early 1990s.",
    details: [
      "First broadly commercial application of AI in business and industry.",
      "Showed both the value and the limits of hand-coded knowledge.",
      "Their collapse caused the second AI winter.",
    ],
    relatedConcepts: ["Expert Systems", "Knowledge Representation", "Symbolic AI"],
  },
  {
    id: "lstm-1997",
    year: "1997",
    sortYear: 1997,
    decade: "1990s",
    title: "LSTM Networks",
    tagline: "Hochreiter & Schmidhuber solve long-range memory in RNNs.",
    category: "Architecture",
    impact: 4,
    figure: "Hochreiter & Schmidhuber",
    summary:
      "Long Short-Term Memory networks introduced gating to let recurrent networks remember information over long sequences, fixing the vanishing-gradient problem. LSTMs powered a decade of sequence modelling — translation, speech, and text — until Transformers arrived.",
    details: [
      "Enabled learning of long-range dependencies in sequential data.",
      "Became the workhorse for translation and speech recognition.",
      "Set the problem (sequence modelling) that Transformers would later master.",
    ],
    relatedConcepts: ["RNN", "LSTM", "Sequence Modelling"],
  },
  {
    id: "deep-blue-1997",
    year: "1997",
    sortYear: 1997,
    decade: "1990s",
    title: "Deep Blue Defeats Kasparov",
    tagline: "IBM's chess computer beats the world champion.",
    category: "Milestone",
    impact: 4,
    figure: "IBM",
    summary:
      "IBM's Deep Blue became the first computer to beat a reigning world chess champion under tournament conditions, defeating Garry Kasparov. A triumph of brute-force search and specialised hardware, it was a landmark cultural moment for machine capability.",
    details: [
      "First machine to beat a world chess champion in a match.",
      "Showcased the power of search + domain-specific engineering.",
      "Shifted public perception of what computers could do.",
    ],
    relatedConcepts: ["Game Playing", "Search", "Heuristics"],
  },
  {
    id: "dl-revival-2006",
    year: "2006",
    sortYear: 2006,
    decade: "2000s",
    title: "Deep Learning Revival",
    tagline: "Breakthroughs in training deep neural networks renew AI research.",
    category: "Deep Learning",
    impact: 4,
    figure: "Geoffrey Hinton",
    summary:
      "Hinton and collaborators showed deep belief networks could be trained layer-by-layer with greedy pre-training, reigniting interest in deep neural networks. Combined with growing data and GPUs, it set the conditions for the deep-learning explosion to come.",
    details: [
      "Renewed credibility for deep architectures after the neural-net winter.",
      "Introduced unsupervised pre-training to initialise deep nets.",
      "Coincided with GPUs making large-scale training feasible.",
    ],
    relatedConcepts: ["Deep Learning", "Pre-training", "Representation Learning"],
  },
  {
    id: "alexnet-2012",
    year: "2012",
    sortYear: 2012,
    decade: "2010s",
    title: "AlexNet & the ImageNet Breakthrough",
    tagline: "Deep learning shatters the ImageNet record.",
    category: "Computer Vision",
    impact: 5,
    figure: "Krizhevsky, Sutskever & Hinton",
    summary:
      "AlexNet, a deep convolutional network trained on two GPUs, cut the ImageNet error rate by almost half and demonstrated decisively that deep learning beats hand-engineered features. This single result kicked off the modern deep-learning era across every domain.",
    details: [
      "Halved the state-of-the-art ImageNet error overnight.",
      "Proved GPUs + big data + deep CNNs is a winning recipe.",
      "Triggered industry-wide adoption of deep learning.",
    ],
    relatedConcepts: ["CNN", "Computer Vision", "GPU Training"],
  },
  {
    id: "word2vec-2013",
    year: "2013",
    sortYear: 2013,
    decade: "2010s",
    title: "word2vec — Word Embeddings",
    tagline: "Mikolov et al. turn words into meaningful vectors.",
    category: "NLP",
    impact: 4,
    figure: "Tomas Mikolov (Google)",
    summary:
      "word2vec learned dense vector representations where semantic relationships became arithmetic ('king − man + woman ≈ queen'). Embeddings became the standard input representation for NLP and a core idea behind how modern models represent meaning.",
    details: [
      "Made distributed word representations fast to train at scale.",
      "Showed semantics can live in vector geometry.",
      "Embeddings remain foundational to search, RAG and LLMs.",
    ],
    relatedConcepts: ["Embeddings", "Word Vectors", "Semantics"],
  },
  {
    id: "gans-2014",
    year: "2014",
    sortYear: 2014,
    decade: "2010s",
    title: "Generative Adversarial Networks",
    tagline: "Goodfellow introduces a new framework for generative modelling.",
    category: "Deep Learning",
    impact: 4,
    figure: "Ian Goodfellow",
    summary:
      "GANs pit a generator against a discriminator in a minimax game, learning to synthesise strikingly realistic images. They dominated generative modelling for years and pushed forward the idea that networks could create, not just classify.",
    details: [
      "Opened the era of high-fidelity image synthesis.",
      "Introduced adversarial training as a powerful learning signal.",
      "Paved the way (conceptually) for today's generative models.",
    ],
    relatedConcepts: ["GANs", "Generative Models", "Adversarial Training"],
  },
  {
    id: "attention-2017",
    year: "2017",
    sortYear: 2017,
    decade: "2010s",
    title: "Attention Is All You Need",
    tagline: "The Transformer architecture is introduced.",
    category: "Architecture",
    impact: 5,
    figure: "Vaswani et al. (Google)",
    summary:
      "The Transformer replaced recurrence with self-attention, allowing models to weigh every token against every other in parallel. It scaled far better than RNNs on modern hardware and became the architecture behind essentially every large language model since.",
    details: [
      "Removed the sequential bottleneck of RNNs — fully parallel training.",
      "Self-attention captures long-range dependencies directly.",
      "The foundation of GPT, BERT, T5 and all modern LLMs.",
    ],
    relatedConcepts: ["Attention", "Transformers", "Self-Attention"],
    links: [{ label: "Read the paper", href: "https://arxiv.org/abs/1706.03762" }],
  },
  {
    id: "bert-2018",
    year: "2018",
    sortYear: 2018,
    decade: "2010s",
    title: "BERT — Bidirectional Pre-training",
    tagline: "Google's BERT sets a new bar for language understanding.",
    category: "NLP",
    impact: 5,
    figure: "Devlin et al. (Google)",
    summary:
      "BERT pre-trained a deep bidirectional Transformer with masked-language modelling, then fine-tuned for downstream tasks. It swept NLP benchmarks and cemented the 'pre-train then fine-tune' paradigm that defines modern language AI.",
    details: [
      "Popularised large-scale self-supervised pre-training for NLP.",
      "Bidirectional context dramatically improved understanding tasks.",
      "Established the transfer-learning recipe used everywhere since.",
    ],
    relatedConcepts: ["BERT", "Pre-training", "Fine-tuning"],
  },
  {
    id: "gpt3-2020",
    year: "2020",
    sortYear: 2020,
    decade: "2020s",
    title: "GPT-3 Released",
    tagline: "Large-scale pretraining demonstrates the power of scale.",
    category: "LLM",
    impact: 5,
    figure: "OpenAI",
    summary:
      "GPT-3's 175 billion parameters showed that simply scaling up data, parameters and compute produces qualitatively new abilities — most strikingly few-shot 'in-context' learning, where the model performs tasks from a prompt alone, with no fine-tuning.",
    details: [
      "Demonstrated emergent few-shot / in-context learning.",
      "Made 'scale is a strategy' the dominant industry thesis.",
      "Its API seeded the first wave of LLM-powered products.",
    ],
    relatedConcepts: ["Large Language Models", "Scaling Laws", "In-context Learning"],
  },
  {
    id: "diffusion-2021",
    year: "2021–22",
    sortYear: 2021,
    decade: "2020s",
    title: "Diffusion Models & CLIP",
    tagline: "Text-to-image generation goes mainstream.",
    category: "Multimodal",
    impact: 4,
    figure: "OpenAI, Stability AI",
    summary:
      "CLIP aligned images and text in a shared space, and diffusion models (DALL·E 2, Stable Diffusion, Midjourney) learned to generate images by iteratively denoising. Together they made high-quality, controllable text-to-image generation widely accessible.",
    details: [
      "Diffusion overtook GANs as the leading image-generation method.",
      "CLIP enabled text-conditioned, open-vocabulary generation.",
      "Open releases (Stable Diffusion) democratised image AI.",
    ],
    relatedConcepts: ["Diffusion Models", "CLIP", "Text-to-Image"],
  },
  {
    id: "chatgpt-2022",
    year: "2022",
    sortYear: 2022,
    decade: "2020s",
    title: "ChatGPT Launch",
    tagline: "Conversational AI goes mainstream.",
    category: "Application",
    impact: 5,
    figure: "OpenAI",
    summary:
      "ChatGPT wrapped an instruction-tuned, RLHF-aligned GPT-3.5 in a simple chat interface and reached 100 million users in two months — the fastest-growing consumer app in history at the time. It turned LLMs from a research curiosity into a daily tool for millions.",
    details: [
      "Brought LLMs to a mass audience through a conversational UI.",
      "Showcased RLHF for helpful, aligned responses.",
      "Ignited the generative-AI product race across the industry.",
    ],
    relatedConcepts: ["RLHF", "Instruction Tuning", "Conversational AI"],
  },
  {
    id: "gpt4-2023",
    year: "2023",
    sortYear: 2023,
    decade: "2020s",
    title: "GPT-4 & the Multimodal Turn",
    tagline: "Frontier models gain vision and stronger reasoning.",
    category: "LLM",
    impact: 5,
    figure: "OpenAI",
    summary:
      "GPT-4 delivered a large jump in reasoning, reliability and exam performance, and accepted images as input. It set off intense competition (Anthropic's Claude, Google's Gemini) and a wave of enterprise adoption built on far more capable models.",
    details: [
      "Major gains on reasoning, coding and professional exams.",
      "Native multimodal (image) input in a frontier model.",
      "Catalysed serious competition among frontier labs.",
    ],
    relatedConcepts: ["Multimodal", "Reasoning", "Alignment"],
  },
  {
    id: "open-llms-2023",
    year: "2023",
    sortYear: 2023,
    decade: "2020s",
    title: "Open-source LLMs (Llama)",
    tagline: "Meta releases Llama, accelerating open research and adoption.",
    category: "Open Source",
    impact: 4,
    figure: "Meta AI",
    summary:
      "Meta's Llama (and Llama 2) put capable, openly-available model weights in the hands of researchers and builders, sparking an explosion of fine-tunes, tooling and on-device deployment. Open models became a genuine counterweight to closed frontier APIs.",
    details: [
      "Made strong LLM weights broadly available to build on.",
      "Seeded a vast open ecosystem of fine-tunes and tooling.",
      "Pushed efficiency research (quantization, LoRA, small models).",
    ],
    relatedConcepts: ["Open Weights", "Fine-tuning", "Quantization"],
  },
  {
    id: "agentic-2024",
    year: "2024",
    sortYear: 2024,
    decade: "2020s",
    title: "Multimodal & Agentic AI Rise",
    tagline: "Models handle text, image, audio and video — and take actions.",
    category: "Multimodal",
    impact: 5,
    figure: "OpenAI, Google, Anthropic, Meta",
    summary:
      "Frontier models became natively multimodal (GPT-4o, Gemini 1.5, Claude 3) with long context windows, while 'agentic' systems began using tools, browsing and writing code to complete multi-step tasks autonomously. Mixture-of-Experts pushed capability up and cost down.",
    details: [
      "Native any-to-any multimodality (text, image, audio, video).",
      "Long-context (up to millions of tokens) unlocked new use cases.",
      "Tool-use and agents moved from demos toward real workflows.",
    ],
    relatedConcepts: ["Agents", "Mixture of Experts", "Tool Use"],
  },
  {
    id: "reasoning-2025",
    year: "2025",
    sortYear: 2025,
    decade: "2020s",
    title: "Reasoning Models & Test-time Compute",
    tagline: "Models 'think' longer to solve harder problems.",
    category: "Frontier",
    impact: 5,
    figure: "OpenAI, DeepSeek, Anthropic, Google",
    summary:
      "A new class of models (OpenAI's o-series, DeepSeek-R1, Claude and Gemini 'thinking' modes) learned to spend more compute at inference time — generating long chains of reasoning before answering. Reinforcement learning on reasoning traces drove large gains in maths, science and code.",
    details: [
      "Shifted scaling from training-only to inference-time compute.",
      "RL on reasoning traces sharply improved hard-problem accuracy.",
      "Open reasoning models (DeepSeek-R1) narrowed the frontier gap.",
    ],
    relatedConcepts: ["Reasoning", "Test-time Compute", "Reinforcement Learning"],
  },
  {
    id: "agi-frontier",
    year: "2025+",
    sortYear: 2026,
    decade: "2020s",
    title: "Toward AGI?",
    tagline: "Researchers push boundaries toward more general, capable systems.",
    category: "Frontier",
    impact: 5,
    summary:
      "The open question of the era: how far does scale, reasoning and agency go? Research now spans general-purpose agents, world models, efficiency, interpretability and the safety and alignment work needed to deploy increasingly capable systems responsibly.",
    details: [
      "Debate over whether current paradigms reach general intelligence.",
      "Growing emphasis on safety, interpretability and alignment.",
      "Efficiency and reliability matter as much as raw capability.",
    ],
    relatedConcepts: ["AGI", "Alignment", "Interpretability"],
  },
];
